/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'
export type InitBridgeParams = {
  portfolio: web3.PublicKey
  mainnetRfq: web3.PublicKey
  defaultChainId: number
  endpointProgram: web3.PublicKey
}

/**
 * @category userTypes
 * @category generated
 */
export const initBridgeParamsBeet = new beet.BeetArgsStruct<InitBridgeParams>(
  [
    ['portfolio', beetSolana.publicKey],
    ['mainnetRfq', beetSolana.publicKey],
    ['defaultChainId', beet.u32],
    ['endpointProgram', beetSolana.publicKey],
  ],
  'InitBridgeParams'
)
