/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { MessagingFee, messagingFeeBeet } from './MessagingFee'
export type MessagingReceipt = {
  guid: number[] /* size: 32 */
  nonce: beet.bignum
  fee: MessagingFee
}

/**
 * @category userTypes
 * @category generated
 */
export const messagingReceiptBeet = new beet.BeetArgsStruct<MessagingReceipt>(
  [
    ['guid', beet.uniformFixedSizeArray(beet.u8, 32)],
    ['nonce', beet.u64],
    ['fee', messagingFeeBeet],
  ],
  'MessagingReceipt'
)
