/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
/**
 * @category enums
 * @category generated
 */
export enum Tx {
  Withdraw,
  Deposit,
  Execution,
  IncreaseAvail,
  DecreaseAvail,
  IxferSent,
  IxferRec,
  RecoverFunds,
  AddGas,
  RemoveGas,
  AutoFill,
  CcTrade,
  ConvertFrom,
  ConvertTo,
}

/**
 * @category userTypes
 * @category generated
 */
export const txBeet = beet.fixedScalarEnum(Tx) as beet.FixedSizeBeet<Tx, Tx>
